<a href="https://colab.research.google.com/github/dimpal2526/Data-Visualization/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


##Introduction to tensors

#creating tensors
 pytorch tensors are created using `torch.tensor()`

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Get tensor back as python int
scalar.item()


7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
matrix = torch.tensor([[7,8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]


tensor([7, 8])

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
#Tensor
Tensor = torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

# Random Tensors

why random tensors?
Random tensors are important because the way many neural networks learn is that they strat with tensors full of number adjust those random numbers to better represent the data



In [16]:
# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6595, 0.2191, 0.8819, 0.1480],
        [0.5532, 0.2380, 0.4108, 0.7423],
        [0.3571, 0.3497, 0.2735, 0.6315]])

In [17]:
random_tensor.ndim

2

In [18]:
random = torch.rand(1, 10, 10)
random

tensor([[[0.6570, 0.7742, 0.1162, 0.0729, 0.7927, 0.4732, 0.5303, 0.9928,
          0.7093, 0.7707],
         [0.7277, 0.8540, 0.0951, 0.2745, 0.8942, 0.7920, 0.4325, 0.2239,
          0.5128, 0.8012],
         [0.0537, 0.0577, 0.1880, 0.7546, 0.2657, 0.7678, 0.1270, 0.4587,
          0.5850, 0.0190],
         [0.7889, 0.4095, 0.6921, 0.3893, 0.6553, 0.0807, 0.6571, 0.5757,
          0.1023, 0.6193],
         [0.8269, 0.8294, 0.3472, 0.4745, 0.5282, 0.3477, 0.4115, 0.5460,
          0.8110, 0.6281],
         [0.4105, 0.6479, 0.4527, 0.8133, 0.5142, 0.9370, 0.8200, 0.6546,
          0.5654, 0.2352],
         [0.9239, 0.7626, 0.8164, 0.4150, 0.1384, 0.3230, 0.6701, 0.7472,
          0.3622, 0.6401],
         [0.0790, 0.2550, 0.4491, 0.5401, 0.4128, 0.2018, 0.4339, 0.0792,
          0.8182, 0.8541],
         [0.9551, 0.4052, 0.8548, 0.9332, 0.9474, 0.0914, 0.6665, 0.4506,
          0.7523, 0.1427],
         [0.4558, 0.5178, 0.7862, 0.9360, 0.2918, 0.4875, 0.7191, 0.7088,
          0.4205,

In [19]:
random.shape

torch.Size([1, 10, 10])

In [20]:
random.ndim

3

In [21]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) #  color (R,G,B),height, width,
random_image_size_tensor

tensor([[[0.5662, 0.2982, 0.0304,  ..., 0.6170, 0.0337, 0.8219],
         [0.3269, 0.6122, 0.1993,  ..., 0.7649, 0.6844, 0.3591],
         [0.4748, 0.2012, 0.6159,  ..., 0.8684, 0.6490, 0.6164],
         ...,
         [0.7368, 0.5858, 0.6874,  ..., 0.7812, 0.7189, 0.0039],
         [0.0626, 0.7967, 0.2286,  ..., 0.7025, 0.6732, 0.8806],
         [0.9455, 0.2999, 0.4462,  ..., 0.0584, 0.2596, 0.5148]],

        [[0.9934, 0.2881, 0.6300,  ..., 0.6612, 0.7327, 0.7081],
         [0.4933, 0.1746, 0.9934,  ..., 0.7114, 0.0902, 0.7913],
         [0.3942, 0.8740, 0.4498,  ..., 0.1566, 0.4046, 0.5191],
         ...,
         [0.6967, 0.0886, 0.4330,  ..., 0.8425, 0.7079, 0.6148],
         [0.1458, 0.9343, 0.4243,  ..., 0.4704, 0.1538, 0.9982],
         [0.6954, 0.0603, 0.1042,  ..., 0.0524, 0.5084, 0.4130]],

        [[0.7187, 0.3322, 0.1886,  ..., 0.8775, 0.2474, 0.8477],
         [0.9447, 0.6909, 0.1597,  ..., 0.1564, 0.0632, 0.0406],
         [0.7952, 0.0110, 0.8158,  ..., 0.4189, 0.3984, 0.

In [22]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [23]:
random_tens = torch.rand(9, 6)
random_tens

tensor([[0.8891, 0.4443, 0.5936, 0.0943, 0.6204, 0.3390],
        [0.0328, 0.9596, 0.9869, 0.6041, 0.8221, 0.5734],
        [0.5285, 0.1852, 0.3994, 0.4750, 0.1085, 0.6778],
        [0.4850, 0.2522, 0.9368, 0.5072, 0.1746, 0.9717],
        [0.8535, 0.3273, 0.8777, 0.8452, 0.6172, 0.9451],
        [0.2132, 0.0203, 0.5734, 0.3390, 0.8530, 0.0390],
        [0.0511, 0.2547, 0.6824, 0.9621, 0.1314, 0.8416],
        [0.9913, 0.9421, 0.0591, 0.6155, 0.7514, 0.0318],
        [0.7787, 0.8519, 0.3659, 0.5374, 0.7050, 0.5082]])

In [24]:
random_tens.shape, random_tens.ndim

(torch.Size([9, 6]), 2)

Zeroes and ones

In [25]:
# create a tensor of all zeroes
zeroes = torch.zeros(3,4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
random_tensor.dtype

torch.float32

In [29]:
zeroes = torch.zeros(size = (4,5), dtype= torch.int32)
zeroes

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

creating a range of tensors and tensor-like

In [30]:
#use torch.range and get deprecated message, use torch.arange()
one_to_ten =torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
torch.arange(start=1, end=1000, step = 23)

tensor([  1,  24,  47,  70,  93, 116, 139, 162, 185, 208, 231, 254, 277, 300,
        323, 346, 369, 392, 415, 438, 461, 484, 507, 530, 553, 576, 599, 622,
        645, 668, 691, 714, 737, 760, 783, 806, 829, 852, 875, 898, 921, 944,
        967, 990])

In [32]:
#create tensor like
ten_zeros =torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatype
**note** Tensor datatype is one ofthe 3 big error you'll run into with pytorch & deep leraining:
1.Tensor not right datatype
2.tensor not right shape
3.tensor not on the right device

In [33]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16,
                               device=None # what device is your tensor on
                               , requires_grad=True)#whether or not to gradients with these operations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16, requires_grad=True)

In [34]:
float_32_tensor.dtype

torch.float16

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16, requires_grad=True)

In [36]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.], dtype=torch.float16, grad_fn=<MulBackward0>)

In [37]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16, grad_fn=<MulBackward0>)

In [39]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16, grad_fn=<MulBackward0>)

##Getting information from tensors - tensor attributes
1.Tensor not right datatype - to do get datatype from a tensor can use `tensor.dtype`
2.tensor not right shape - to get shape from a tensor `tensor.shape`
3.tensor not on the right device - to get device from a tensor , can use `tensor.device`



In [40]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9712, 0.2812, 0.4746, 0.6470],
        [0.4836, 0.0030, 0.9069, 0.2659],
        [0.7888, 0.3517, 0.7256, 0.9897]])

In [41]:
#find out the detail of some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor  : {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.9712, 0.2812, 0.4746, 0.6470],
        [0.4836, 0.0030, 0.9069, 0.2659],
        [0.7888, 0.3517, 0.7256, 0.9897]])
Datatype of tensor: torch.float32
Shape of tensor  : torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors(tensor operatio)

Tensor operation include:
1. Addition
2. Subtraction
3. Multiplication(element_wise)
4. Division
5. Matrix Multiplication


In [42]:
#create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [43]:
#multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
# subtract
tensor - 10

tensor([-9, -8, -7])

In [46]:
# try out pytorch in-built function
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [48]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

### Matrix Multiplication
Two main ways of performing multiplication in neural network and deep learning:


1.   Element wise multiplication
2.   Matrix Multiplication(dot product)

There are two main rules that performing matrix multiplication needs  to satisfy:
1. tne **inner dimension** must match:
`(3, 2) @ (3,2)` wont work
`(2, 3) @ (3,2)` will work
`(3, 2) @ (2, 3)` will work
2. the resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) * (3, 2)` -> `(2, 2)`
* `(3, 2) *(2, 3)` -> `(3, 3)`







In [49]:
#Element wise multiplication
tensor

tensor([1, 2, 3])

In [50]:
print(tensor, "*", tensor)
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [51]:
# Matrix Multiplication
torch.matmul(tensor, tensor)


tensor(14)

In [52]:
tensor

tensor([1, 2, 3])

In [53]:
#Matrix multiplication ny hand
1*1 + 2*2 + 3*3

14

In [54]:
%%time
value = 0
for  i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.19 ms, sys: 0 ns, total: 1.19 ms
Wall time: 1.95 ms
Compiler : 144 ms


In [55]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 47 µs, sys: 8 µs, total: 55 µs
Wall time: 59.4 µs


tensor(14)

In [56]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.3191, 0.4145],
        [0.4002, 0.3736]])

In [57]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.5278, 0.2253, 0.5726],
        [0.3534, 0.5661, 0.6682],
        [0.2531, 0.3942, 0.4708]])

In [58]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 10))

tensor([[0.5740, 0.3789, 0.6547, 0.3348, 0.6356, 0.8522, 0.9051, 0.6361, 0.8455,
         0.4538],
        [0.2122, 0.1398, 0.2417, 0.1234, 0.2350, 0.3152, 0.3347, 0.2352, 0.3129,
         0.1678],
        [0.3531, 0.1661, 0.3036, 0.1159, 0.3941, 0.5496, 0.5744, 0.3799, 0.5891,
         0.2731]])

In [59]:
torch.matmul(torch.rand(3, 2), torch.rand(4, 3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 4x3)

In [ ]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

In [ ]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10))

## one of the most common error in deep learning : shape errors

In [ ]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.matmul = (tensor_A, tensor_B) # torch.mm is same as matmul (it's an alias for writing less code)



## To fix out tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**
A **transpose** swithches the axes or dimension of a given tensor.

In [ ]:
tensor_B

In [ ]:
tensor_B.shape

In [ ]:
tensor_B.T

In [ ]:
tensor_B.shape

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B.T)

In [ ]:
# The matrix multiplicatiion operation works when tensor_B is transposed
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A = {tensor_A.shape} (same shape as above) , tensor_B.T = {tensor_B.T.shape}")
print(f"multiplying : {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must watch")
print("output:/n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\n output shape : {output.shape}")

## Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x

In [ ]:
# find the min
torch.min(x), x.min()

In [ ]:
# find the max
torch.max(x), x.max()

In [ ]:
#find the mean - note: the torch.mesn() function requires a tensor offloat32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
#Find the sum
torch.sum(x), x.sum()

#Finding the positional min and max

In [ ]:
x


In [ ]:
#find the position in tensor that has the minimum  value with argmin() -> return the index of minimum value occur
x.argmin()

In [ ]:
x.argmax()

# Reshaping, Stacking, Squeezing and Unsqueezing tensors

* Reshaping - reshapes an  input tensor to a defined shape
* view - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensor on top of each other(vstack) or side by side(hstack)
* squeeze - removes all `1 ` dimension from a tensor
* unsqueeze - add a `1` dimension to a targettensor
* permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
#create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

In [ ]:
x = torch.arange(1., 13.)
x, x.shape

In [ ]:
x_reshaped = x.reshape(3, 4)
x_reshaped, x_reshaped.shape

In [ ]:
# change the view
x = torch.arange(1., 10.)
z = x.view(1, 9)
z, z.shape

In [ ]:
#changing z changes x (because a view of a tensor shares the same memory as the original insist)
z[:, 0] = 5
z, x

In [ ]:
#stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked


In [ ]:
x_stacked = torch.hstack([x, x, x, x])
x_stacked

In [ ]:
x_stacked = torch.vstack([x, x, x, x])
x_stacked

In [ ]:
#torch.squeeze() = remove all single dimension from a target tensor
x_reshaped


In [ ]:
x_reshaped.shape

In [ ]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

In [ ]:
x = torch.arange(1, 11)
x

In [ ]:
x.squeeze()

In [ ]:
x = torch.arange(1., 10.)
z = x.view(1, 9)
z.squeeze(), z.shape

In [ ]:
z

In [ ]:
#torch.squeeze() = remove all single dimension from a target tensor
print(f"previous tensor: {z}")
print(f"previous shape : {z.shape}")
#  remove extra dimension from z
z_squeezed = z.squeeze()
print(f"New tensor: {z_squeezed}")
print(f"New shape:{z_squeezed.shape}")


In [ ]:
#torch.unsqueeze() = add a single dimension to a target tensor at a specific dim(dimension)
print(f"previous tensor: {z_squeezed}")
print(f"previous tensor: {z_squeezed.shape}")

#ADD AN EXTRA DIMNESION WITH UNSQUEEZED
z_unsqueezed = z_squeezed.unsqueeze(dim = 0)
print(f"New tensor: {z_unsqueezed}")
print(f"New shape:{z_unsqueezed.shape}")



In [ ]:
z_unsqueezed = z_squeezed.unsqueeze(dim = 1)
print(f"New tensor: {z_unsqueezed}")
print(f"New shape:{z_unsqueezed.shape}")


In [ ]:
# torch.permute - rearrange the dimension of a target tensor in a specified order
x_original = torch.rand(size = (224, 224, 3)) #height, width, with color channels

# permute the  original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 1->0

print(f"previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}") #color channel, height, width


In [ ]:
x_original[0, 0, 0]

In [ ]:
x_original[1, 0]

In [ ]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

## Indexing (selecting data from tensor)
 Indexing with pytorch  is similar to indexing with numpy

In [ ]:
#create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)#  1batch or outer dimension, 3 rows, 3columns
x ,x.shape

In [ ]:
# Let's index an our new tensor
x[0]


In [ ]:
#Let's index on the middle bracket(dim =1)
x[0][0]

In [ ]:
#Let's index on the most inner bracket (last dimension)
x[0][0][0]

In [ ]:
x[0][1][2]

In [ ]:
x[0][2][2]

In [ ]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

In [ ]:
x[:, :, 2]

In [ ]:
#Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x [:, :, 1]

In [ ]:
#Get all values of 0th dimenssion but only the 1 index of 1st and 2nd dimension
x [:, 1, 1]

In [ ]:
#Get index o of oth and 1st dimension and all values of 2nd dimension
x[0, 0, :]

In [ ]:
# Index on x return 9
print(x[:, 2, 2])
#index on x  to return 3, 6, 9
print(x[:, :, 2])

## Pythorch tensor & Numpy
Numpy is a popular scientific python numerical computing library.

And because of this, pytorch has functionality to interact with  it.
 * Data in numpy, want in pytorch teensor -> `torch.from_numpy(ndarray)`
 * pytorch tensor -> Numpy -> `torch.tensor.numpy()`

In [ ]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

In [ ]:
array.dtype

In [ ]:
tensor.dtype

In [ ]:
torch.arange(1.0, 8.0).dtype

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) #warning have been coverting from numpy -> pytorch , pytorch reflects numpy's default datatype of float64 unless specified  otherwise
array, tensor

In [ ]:
# change the vaqlue of the array, what will this do to `tensor`?
array = array + 1
array, tensor

In [ ]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [ ]:
#change the tensor what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor


###Reproducbility (trying to take random out of random)

In shorthow a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again ...


To reduce the randomness in neural network and pytorch comes the concept of a **random seed**
Essentially what the random seed does is "flavour" the randomness


In [ ]:
torch.rand(3, 3)

#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

In [ ]:
# Let's make some random but reproducible tensors
import torch
  # set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)



##Runing tensor and pytorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA = NVIDIA - Pytorch working behind hte scenes to make everything hunky dory(good)


Google Colab for a free GPU.(options to upgrade)
2. use your own cpu - takes a little a bit of setup and requires the investment of purchasing a GPu , there's lots of option......
3.  use cloud computing  - GCP, AWS, AZURE, these services allow you to rent computers on the cloud and access them

In [ ]:
!nvidia-smi

##checkfor GPU access with pytorch


In [ ]:
import  torch
torch.cuda.is_available()

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

In [ ]:
# count number of devices
torch.cuda.device_count()

# putting tensors (and models ) on the Gpu

the reason we want our tensors / modelson the GPU because using a Gpu result in faster computations



In [ ]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

#tensor not on GPU
print(tensor, tensor.device)


In [ ]:
# move tensor to gpu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu