<a href="https://colab.research.google.com/github/dimpal2526/Data-Visualization/blob/main/00_pytorchexercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Create a random tensor with shape (7, 7).
import torch


In [3]:
tensor = torch.rand(7,7)
tensor

tensor([[0.7225, 0.8355, 0.8423, 0.4127, 0.7670, 0.3024, 0.2661],
        [0.0377, 0.3303, 0.6937, 0.1856, 0.9503, 0.8500, 0.8243],
        [0.6479, 0.7551, 0.9883, 0.1614, 0.8357, 0.5933, 0.8823],
        [0.5499, 0.8511, 0.0762, 0.3474, 0.2059, 0.9410, 0.5967],
        [0.0920, 0.2893, 0.9294, 0.3533, 0.5661, 0.7029, 0.4807],
        [0.8682, 0.4816, 0.7677, 0.4458, 0.6219, 0.9185, 0.5660],
        [0.9020, 0.8711, 0.6303, 0.9644, 0.4144, 0.5602, 0.1912]])

In [7]:
#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
tensor1 = torch.rand(2,7)
tensor2 = torch.rand(1,7)

tensor2_transpose = tensor2.T
print(tensor1)
print(tensor2)
print(tensor2_transpose)
multiply = torch.matmul(tensor1, tensor2.T)
print(multiply)

tensor([[0.6936, 0.5352, 0.5513, 0.3262, 0.2582, 0.6595, 0.5691],
        [0.8560, 0.2654, 0.9766, 0.6542, 0.9512, 0.6959, 0.3520]])
tensor([[3.3660e-01, 5.8717e-04, 7.9208e-01, 3.0828e-01, 8.2951e-01, 9.1887e-01,
         9.4194e-01]])
tensor([[3.3660e-01],
        [5.8717e-04],
        [7.9208e-01],
        [3.0828e-01],
        [8.2951e-01],
        [9.1887e-01],
        [9.4194e-01]])
tensor([[2.1272],
        [3.0235]])


In [11]:
torch.manual_seed(0)
tensor = torch.rand(7,7)
tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [12]:
tensor1 = torch.rand(2,7)
tensor2 = torch.rand(1,7)

tensor2_transpose = tensor2.T
print(tensor1)
print(tensor2)
print(tensor2_transpose)
multiply = torch.matmul(tensor1, tensor2.T)
print(multiply)

tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056],
        [0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]])
tensor([[0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801]])
tensor([[0.6511],
        [0.7745],
        [0.4369],
        [0.5191],
        [0.6159],
        [0.8102],
        [0.9801]])
tensor([[2.9746],
        [1.8807]])


In [14]:
#Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the do
# set cpu random seed
torch.manual_seed(0)

# if using cuda , set gpu seed too
if torch.cuda.is_available():
  torch.cuda.manual_seed(0)

In [16]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

torch.manual_seed(1234)

tensor_a = torch.rand(2, 3)
tensor_b = torch.rand(2, 3)

#send to gpu if available
device = torch.device("cuda" if torch.cuda.is_available()
else"cpu")

tensor_a = tensor_a.to(device)
tensor_b = tensor_b.to(device)


In [18]:
#Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
tensor_b_t = tensor_b.T
result = torch.matmul(tensor_a, tensor_b.T)
print(result)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])


In [19]:
#Find the maximum and minimum values of the output of 7.
#Find the maximum and minimum index values of the output of 7.

min_value = torch.min(result)
max_value = torch.max(result)
print(min_value)
print(max_value)

tensor(0.3647)
tensor(0.5617)


In [20]:
#Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

#set seed
torch.manual_seed(7)

tensor_1 = torch.rand(1,1,1,10)
tensor_2 = tensor_1.squeeze()

print("First tensor", tensor_1)
print("shape", tensor_1.shape)

print("second tensor", tensor_2)
print("shape", tensor_2.shape)

First tensor tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
shape torch.Size([1, 1, 1, 10])
second tensor tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
shape torch.Size([10])
